# Site settings
title: Javier Lo | UI/UX Designer
email: hello@javierlo.com
description: > # this means to ignore newlines until "baseurl:"
  Hello my name is Javier, I'm a ux and ui designer specializing in mobile/desktop application and websites.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://javierlo.com" # the base hostname & protocol for your site
twitter_username: brrrger
github_username:  surgeonist

# Build settings
markdown: kramdown
